import type { NextPage } from 'next'
import Head from 'next/head'
import { Header } from '../components/Home/Header'
import { Footer } from '../components/Home/Footer'
import { GetInTouch } from '../components/Contact/GetInTouch'

const Contact: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <GetInTouch />
      </main>

      <Footer />
    </div>
  )
}

export default Contact
